spring.application.name=backend-sistema-LPE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=S{DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

spring.security.enabled=false